#!/usr/bin/env sh
export MISSION_DIR="$GSH_ROOT/missions/intermediate/06_control-C"
export TEXTDOMAIN="intermediate,06_control-C"
exec "$GSH_ROOT/missions/intermediate/06_control-C/Charmiglio.sh" "$@"
